### ISSUE TITLE
"Check Now" button causing application to crash

### ISSUE THREAD

**Issue by mattseemon** [mattseemon/todo.txt-WPF#2]
"Check Now" for update button causing the whole application crash with the following error message.

2016-09-06 07:31:44.4353|Fatal|AppBootstrapper: An unhandled exception occured, opeing the crash report.: System.NullReferenceException: Object reference not set to an instance of an object.
   at Seemon.Todo.ViewModels.OptionsViewModel.<DoUpdateNow>d__124.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mattseemon** [comment]
Fixed issue with missing reference to AppUpdater Instance in OptionsViewModel.

**Comment by mattseemon** [comment]
Issue still persists.
